#You will fill this in yourself for practice
#Ultimately it should build and clean three executable programs
CC=gcc -std=c11

all: bit_logical               #other program executables will go here


bit_logical: bit_logical.c binary_convert.c binary_convert.h


clean:
